# 配置文件

DAILY_TIME: "14:00" # 每日定时发送时间。该时间为系统时间，如果当前系统时间不为北京时间需要自行进行换算

START_DATE: "2023-05-01" # 纪念日
CITY: "重庆"

BIRTHDAY:
  - "10-06"

APP_ID: "wx4d64c8b999e1d7ae"
APP_SECRET: "0c2952f1a9792b5a28fec5be6f86c9cf"

USER_ID: 
  - "oOF-p5vQcJFn27X60n7SVVpuXexQ"
  - "oOF-p5oqlxZLg1OsnjRSKCyy1Huw" # 你可以通过配置多个USER_ID来设置多个接受者，如果接受者只有一人删除本行即可
TEMPLATE_ID: "s--Nc9F_GgkbQYViVrGP_sCjCbQNaHQ-izvqV-jSI-0"
